"""Add SurveyRoute and route_id to StreetAnalysis

Revision ID: 39b9b99f633c
Revises: 
Create Date: 2026-04-11 15:39:43.695078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b9b99f633c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_routes_id'), 'survey_routes', ['id'], unique=False)
    op.drop_table('spatial_ref_sys')
    op.add_column('street_analyses', sa.Column('route_id', sa.Integer(), nullable=True))
    op.add_column('street_analyses', sa.Column('order_index', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_street_analyses_route_id'), 'street_analyses', ['route_id'], unique=False)
    op.create_foreign_key(None, 'street_analyses', 'survey_routes', ['route_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'street_analyses', type_='foreignkey')
    op.drop_index(op.f('ix_street_analyses_route_id'), table_name='street_analyses')
    op.drop_column('street_analyses', 'order_index')
    op.drop_column('street_analyses', 'route_id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_survey_routes_id'), table_name='survey_routes')
    op.drop_table('survey_routes')
    # ### end Alembic commands ###
